### ISSUE TITLE
Tracking pack number changes

### ISSUE THREAD

**Issue by ghost** [themadmrj/ircapp#11]
Hi, not sure if this is fixable. On rather large downloads I don't tend to download it in one go and sometimes when I restart the app the next day, it starts downloading an entirely different file, so I'm guessing the pack number has changed. Would be nice if it somehow tracked this change and carry on downloading the same file, or at least do a filename check and then re-search to pick up the same file and carry on where it left off.
Many thanks, excellent app BTW!

**Comment by jonasN5** [comment]
Hi,

yes I've already had this problem a few times. It is indeed the pack number that has changed and sadly, there is no way to prevent it, since it's all about IRC protecting anonymity. However, I could indeed try to implement a system check on a resume:
-on resume, check if new file corresponds to the old file
-if not, search for the old file and resume if match found
-else, leave it
It's an open project, so as always, feel free to write the lines if you want to. Otherwise I'll take care of it when I find the time. I just started with a new job, so it'll probably be a while since it's not urgent (bug fixing).
You're welcome for it :)
