### ISSUE TITLE
Install from source on windows

### ISSUE THREAD

**Issue by bengalih** [themadmrj/ircapp#12]
I'm trying to "hack" a few changes into the program to meet my use case.  IRCApp is the closest thing I have found to meet my needs, but there are a few things I'm trying to get working on the Windows package.

1) Transfer completed/extracted files to an alternate directory
2) Trigger an external script on completion
3) (possibly) trigger an API call to an another application upon completion.

I was on my way to getting these things going when I realized that one feature i desperately needed was some type of password protection on the site so that it isn't totally accessible when exposed via external IP.  I couldn't figure out how to do this with the windows packaged version, and was trying to install from source as I found some code regarding the website that doesn't seem to be exposed the same way in the Windows distribution.

I was able to install most modules in python 3.6, but the miniupnpc module won't install/build properly and there seems to be a lot of issues with that.

I'm hoping for some kind of guidance on either how I might implement a password page or see what your investment in time may allow.

thanks

**Comment by jonasN5** [comment]
Hi,

i'm pleased to see more users use IRCapp. What's what you're trying to build? I'm curious.
Regarding to your problem, it's a Django based application. Have you tried implementing a simple user based login verification? 
Kind regards,

J.

**Comment by bengalih** [comment]
Hi thanks for the quick response.  Sorry for posting on the issues board...I couldn't find any other good contact info.  I just finished installing the Windows package again to give this another try, but it looks like this was packaged with something like py2win and a lot of the code seems to be in compiled form in the library.zip.  So I can't really customize to my hearts content :/

I'm hoping to use your app in conjunction with internet based PVR recording tools.  Sonarr (for TV) and Radarr or CouchPotato (movies).
Here are the main stumbling blocks.

1) Need to be able move completed/extracted downloads when 100% finished to a "finished" directory.  This is to prevent any possible copying/moving of files before they complete.  I pretty much figured this out with some os.renames statements strategically placed in the downloads.py

2) Need to trigger an external app when #1 is complete.  I think a subprocess.call after those move statements it all that is needed.  This external app could be another python script, bat file, powershell, or shell script...etc...whatever the base system can handle.

3) Need a password login.  Can be very simple, but I want to expose this to the internet like my other integrated apps without a VPN.  I can't figure out how to do this.  I tried .htaccess, but this doesn't use Apache, and I tried something called django-lockdown.  I installed that module into the project and configured it, but it fails on something about requiring a session (or something to that effect).  

If I can get #3 done then I will work more on polishing #1 and #2.

Additionally, I might also want to add the following so that I don't need it in the external script:

4) Calling the JSON/API of the PVR application.  This would be a simple JSON call with some parameters about the filename/location.

5) Calling the subliminal.py modules after download to try to find subtitles.  If I wanted to get fancy here I could first try to scan the downloaded file to see if it was a video file, but I don't know exactly how yet (though I expect there is a python lib for it).

6) Have some sort of regular expression handler to move to different completed directories as per #1 above.  This would allow one to drop TV episodes (SXXEXX) into one location and Movies into another.

I have a few other general comments about features/usability of the basic app, but I can get past all that to have a reliable xdcc downloader I can access over a web page and automatically route my downloads/call an external app.

thanks for your time!

oh...and if I didn't mention I'm a total hack/dilettante with this stuff - so things aren't always totally clear to me :)

**Comment by jonasN5** [comment]
Hi,

I don’t remember if I used cx_Freeze or py2exe, I think I tried both due to some compiling issues regarding miniupnpc. But anyways, you should start from the source code in Github and once it works, figure out the compiling part. Yes, a Sickbeard module for IRCapp’d be great, I couldn’t find to time nor the energy to keep developing it without further input.

For #3, IRCapp uses Cherrypy. Either you implement Apache and run the cherrypy server behind it to use .htaccess, or you find another way. Seems to me the Django-lockdown is a viable solution so let’s figure out exactly why it doesn’t work. Did you use the framework wide blockage or decorators for each view?
Also, what do you want to control exactly? Who do you want to prevent accessing it?

As for external APIs, IRCapp already uses ixirc as it’s search engine, exactly by sending a request to its API and receiving a json response.

One comment: I wanted to implement the SSL feature but didn’t find the time. I suppose that’d be good to add with it. Also, atm anyone can send you anything. Perhaps some control over the file reception would be a good idea (for instance file type, don’t accept .exe or script types except if specified).

Feel free to write again,

J.

**Comment by bengalih** [comment]
The general problem is I can't get miniupnpc compiled on my windows box, so I can't run from source.  I have to run from the  windows package so alot of the code is in the library.zip in compiled form.

Sorry for the noob question - but how do cherrypy and django interact?  Aren't they both web frameworks?  I thought this was using django...so I'm not sure how cherrypy comes into play.

I followed this guy:
http://www.gyford.com/phil/writing/2012/01/24/password-django.php

And just tried to implement the lockdown by putting the first section there into my settings.  Ofc I also had to get lockdown installed first.  I can try to set it up again and then let you know exactly the error I was getting.

Like I said I'm a beginner with most all of this except basic python (which I'm a hack at as most of my scripting experience is not OOP).  I'm in the middle of a basic django tutorial to try and learn a little more of that component.  If you are willing to point me in the right direction on things I may just decide to make this a pet project to get myself up to speed on some things I'd like to learn anyway :)

**Comment by bengalih** [comment]
Ok...so I figured out the lockdown.  I'm not sure if I did it right, and it isn't that pretty...but it is working.
So I installed lockdown on my standalone py3 installation and copied the lockdown folder to the IRCApp folder.  I enabled the lockdown as described here:

https://github.com/Dunedan/django-lockdown

specifically I added the following to settings.py

```
INSTALLED_APPS = (
    'django.contrib.staticfiles',
    'core',
    'lockdown',	
)

MIDDLEWARE_CLASSES = (
    # ...
    'lockdown.middleware.LockdownMiddleware',
)
LOCKDOWN_PASSWORDS = ('mypass', )
LOCKDOWN_FORM = 'lockdown.forms.LockdownForm'
```

Doing that gave me a django error page about lockdown needing the django sessions framework.  I hunted a bit and found information about it and how to enable it.  Without access to the database (assuming there is one), I used file backed sessions.  In the end my additional config looked like this:


```
INSTALLED_APPS = (
    'django.contrib.staticfiles',
    'core',
    'lockdown',	
)

MIDDLEWARE_CLASSES = (
    # ...
    **'django.contrib.sessions.middleware.SessionMiddleware',**
    'lockdown.middleware.LockdownMiddleware',
)
LOCKDOWN_PASSWORDS = ('mypass', )
LOCKDOWN_FORM = 'lockdown.forms.LockdownForm'
**SESSION_ENGINE = 'django.contrib.sessions.backends.file'**
```

Once I had that setup I had a very basic login form page that seemed to adequately restrict me from opening the app until I entered the valid password.  With this in place I'm going to try and get some of my other changes in place.

Is there anyway you could release a windows version that wasn't compiled completely?  Perhaps only compile the miniupnpc pieces (since they seem to be problematic)?  That way, anyone can make changes to the code as needed?  I don't think I can attempt SSL without that...

thanks

**Comment by jonasN5** [comment]
> but how do cherrypy and django interact? Aren't they both web frameworks? I thought this was using 
 django...so I'm not sure how cherrypy comes into play

IRCapp uses Django as it's web framework to generate views and handle user interactions. It uses Cherrypy as it's web server to be able to run the app in your browser and access it via URLs.

> Like I said I'm a beginner

Dude... I've never studied programming... just work your ass off and you can achieve anything!

> Without access to the database (assuming there is one)

Yes, there is a basic sqlite database. Check the settings file for that. The database is generated in the usual user directory.

> Is there anyway you could release a windows version that wasn't compiled completely? Perhaps only compile the miniupnpc pieces (since they seem to be problematic)?

I still don't get it. I gather you can't compile it yourself, which I can understand because I needed quite some time myself to set it up using external software for Windows. But before you compile you're still supposed to check if everything works, e.g. run main.py manually and test it. You test every feature (including SSL) and THEN you compile. So basically, you only need me to compile once everything runs smoothly with uncompiled files :)

**Comment by bengalih** [comment]
> I still don't get it. I gather you can't compile it yourself, which I can understand because I needed quite some time myself to set it up using external software for Windows. But before you compile you're still supposed to check if everything works, e.g. run main.py manually and test it. You test every feature (including SSL) and THEN you compile. So basically, you only need me to compile once everything runs smoothly with uncompiled files :)

Ok - maybe I'm not being clear or misunderstanding something.  I can either download the windows package or I can just git clone the source here.  If I download the windows package then a lot of the code is in compiled form in the library.zip.  Therefore I can't modify it.  The main.py is a good example...I couldn't find the area for initializing on the main IP in the windows code, because it was compiled in the library.

When I git clone the source here I am unable to get it to run.  I had some issues with the rar dll which I eventually got figured out, but I can't install the miniupnpc components on my windows system.  I looked for about 30 minutes for solutions and just got ran in circles.  So I can't run it from source on Windows.

am I missing an alternative?

**Comment by jonasN5** [comment]
Yes that's normal. You're not supposed to modify a compiled package. We
need to figure out why miniupnpc doesnt work. It should only be the one .py
lib if I remember correctly. What is the exact python error you get?

Le 8 sept. 2017 20:41, "bengalih" <notifications@github.com> a écrit :

I still don't get it. I gather you can't compile it yourself, which I can
understand because I needed quite some time myself to set it up using
external software for Windows. But before you compile you're still supposed
to check if everything works, e.g. run main.py manually and test it. You
test every feature (including SSL) and THEN you compile. So basically, you
only need me to compile once everything runs smoothly with uncompiled files
:)

Ok - maybe I'm not being clear or misunderstanding something. I can either
download the windows package or I can just git clone the source here. If I
download the windows package then a lot of the code is in compiled form in
the library.zip. Therefore I can't modify it. The main.py is a good
example...I couldn't find the area for initializing on the main IP in the
windows code, because it was compiled in the library.

When I git clone the source here I am unable to get it to run. I had some
issues with the rar dll which I eventually got figured out, but I can't
install the miniupnpc components on my windows system. I looked for about
30 minutes for solutions and just got ran in circles. So I can't run it
from source on Windows.

am I missing an alternative?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/themadmrj/ircapp/issues/12#issuecomment-328183208>, or mute
the thread

**Comment by bengalih** [comment]
I am trying to install it via pip on my python 3.6 install.  As stated all the other packages you recommend installing I am able to but this one I get the following:

```
D:\Python36-32\Scripts>pip3.exe install miniupnpc
Collecting miniupnpc
  Using cached miniupnpc-2.0.2.tar.gz
Installing collected packages: miniupnpc
  Running setup.py install for miniupnpc ... error
    Complete output from command d:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HTPC-U~1\\AppData\\Local\\Temp\\pip-build-3yg_l9cv\\miniupnpc\\setup.py';f=getattr(to
kenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HTPC-U~1\AppData\Local\Temp\pip-kx4fo8sc-record\install-r
ecord.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "d:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HTPC-U~1\\AppData\\Local\\Temp\\pip-build-3yg_l9cv\\miniupnpc\\setup.py';f=getattr(tokenize, 'open', open)(__
file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HTPC-U~1\AppData\Local\Temp\pip-kx4fo8sc-record\install-record.txt --single-versi
on-externally-managed --compile" failed with error code 1 in C:\Users\HTPC-U~1\AppData\Local\Temp\pip-build-3yg_l9cv\miniupnpc\
```
