### ISSUE TITLE
Parallel download support

### ISSUE THREAD

**Issue by stefanmb** [themadmrj/ircapp#7]
In my opinion the main missing feature in `IRCapp` is support for parallel downloads. I had a brief look at the code and I think it could be added reasonably easy on the server side but the UI will need some refactoring. In particular, the logic for retries would likely have to be moved to the server backend to keep things tidy.

@themadmrj  Is this a feature you are interested in? Should I investigate adding it? Do you have any thoughts regarding this issue?

Thanks!

**Comment by jonasN5** [comment]
The main thought at the beginning was just to implement a quick and easy to understand solution for any user. I knew I was restraining IRC's power and requirements given the occasional absence of package availability.
To be honest, I was simply waiting for some feedback before putting any further thought and energy/time into it. So yes. I created this app for everyone anyways so I'd be glad to receive you're proposal for implementing an unlimited amount of simultaneous downloads. I'll make the necessary UI changes once you're there. I'll probably fix some other various minor UI bugs originating from the javascript. Thanks a lot for your interest, I'm sure we can make IRCapp even better !
By the way, I know a lot could be done better. I didn't study informatics at all and learned everything by myself. So if you have other recommendations, feel free to share :)

**Comment by jonasN5** [comment]
After giving some thought, here's my input : there are 3 main tasks to achieve proper simultaneous downloads.
1 : change the download initialization. Currently, for every new download, a new instance (and therefore a new bot with a new nickname) is launched. The irc package allows one single bot to exist on multiple channels. Download.py must be modified in order to instantiate one bot that will log into separate channels when another package is requested through IRCapp.
2 : rewrite the queue management system. Currently everything is managed client side with javascript. While this was an easy solution for a single download queue system, it won't work with multiple parallel downloads. Therefore, like you pointed it out, it needs to be transposed server side. The best way to manage the queuing system properly to my mind is by adding a function to check the queue database (whether a download is already ongoing on a specific channel). This function should be called every time a download ends (on completion, cancellation, interruption).
3 : adapt the UI to match the changes. I think I will keep the current system, meaning queued items above downloading items above history. Some sort of tag should also show which queued item goes with which downloading item, since they will be channel specific.

**Comment by stefanmb** [comment]
Agreed on **(1)** and **(2)**. Another advantage of pooling connections per channel would be to avoid rapid disconnection/reconnection to the same channel for subsequent downloads or retries. We should try to prevent that kind of behaviour as much as possible to avoid annoying channel ops. I'm not entirely sure how this affects the threading model, but the `irc` package appears to take care of that internally with the reactor pattern. I'll look into it today.

For **(3)** I think the queue/history can be pretty much channel agnostic. The way I thought of this is that you can set a maximum number of downloads (say 4 by default) and then IRCapp will simply start the next 4 downloads, keeping the order the user queued them in. The UI could look pretty much the same as it does now but with multiple downloads at the bottom. There are, of course, server-side complications - like multiple items queued for the same bot, the order of retries, and so on. I'll think about it.

**Comment by jonasN5** [comment]
I added a new function to IRCapp : direct file transfer between two clients. Right now the function works, but not all end user problems have been taken care of. I will add the function to github as soon as the main objectives have been reached, e.g. (1) and (2). I will now look into (1).

**Comment by jonasN5** [comment]
Version 2.0 is online and takes care of everything.
